### ISSUE TITLE
BUG: Repartitioning with sample_fraction raises an error in case partition size * sample_fraction < 1

### ISSUE THREAD

**Issue by abdullah-secer-thg** [mwiebusch78/padawan#1]
**Minimal reproducible example:**
```python
import polars as pl
import padawan
import numpy as np

np.random.seed(0)
df = pl.DataFrame({'ix': np.random.randint(1, 5, 10), 'val': range(10)})
padawan.from_polars(df, index_columns=('ix',)).repartition(2).repartition(1, sample_fraction=0.1).collect()
```
**Description:**
The above code raises "ValueError: sizes has the wrong length" as the `sample(frac=frac)` function of polars produces no rows when sample size * frac is less than 1. This happens when the partition size * sample_fraction is less than 1

https://github.com/mwiebusch78/padawan/blob/0d5f12c926cf1cce8bb4886059a343eeaaa3ec7b/src/padawan/repartitioned_dataset.py#L49C14-L49C14

**Expected behavior:**
It should return the original `df` regardless of partition size

**Installed versions:**
```
padawan==0.8
polars==0.18.15
numpy==1.25.2
```

**Comment by mwiebusch78** [comment]
Resolved in 0.8.1
